### ISSUE TITLE
[1.12-Silent Gems] Crashing while game is booting up.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/SilentGems#169]
Forge Version: forge-14.21.0.2365

**Here's the crash report:**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  RebornCoreASM (RebornCore-1.12-3.1.0.55-universal.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 6/26/17 1:21 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/silentchaos512/gems/client/render/ToolModel
	at net.silentchaos512.gems.item.ToolRenderHelper.onModelBake(ToolRenderHelper.java:275)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_186_ToolRenderHelper_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:806)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:365)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.silentchaos512.gems.client.render.ToolModel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IPerspectiveAwareModel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.IPerspectiveAwareModel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.silentchaos512.gems.item.ToolRenderHelper.onModelBake(ToolRenderHelper.java:275)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_186_ToolRenderHelper_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:806)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:365)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1692024096 bytes (1613 MB) / 2959605760 bytes (2822 MB) up to 7158628352 bytes (6827 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7680m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.0.2365 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2365.jar) 
	UCHIJA	forge{14.21.0.2365} [Minecraft Forge] (forge-1.12-14.21.0.2365.jar) 
	UCHIJA	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJA	thedragonlib{1.12-4.0.1} [TheDragonLib] (thedragonlib-1.12-4.0.1.jar) 
	UCHIJA	armorplus{1.12-11.2.0.5-alpha} [ArmorPlus] (armorplus-1.12-11.2.0.5-alpha.jar) 
	UCHIJA	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJA	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCHIJA	chameleon{1.12-4.0.1} [Chameleon] (Chameleon-1.12-4.0.1.jar) 
	UCHIJA	chesttransporter{2.8.2} [Chest Transporter] (ChestTransporter-1.12-2.8.2.jar) 
	UCHIJA	cyclopscore{0.10.6} [Cyclops Core] (CyclopsCore-1.12-0.10.6.jar) 
	UCHIJA	commoncapabilities{1.3.3} [CommonCapabilities] (CommonCapabilities-1.12-1.3.3.jar) 
	UCHIJA	controlling{3.0.0} [Controlling] (Controlling-3.0.0.jar) 
	UCHIJA	cosmeticarmorreworked{1.12-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.12-v1.jar) 
	UCHIJA	craftingtweaks{8.1.1} [Crafting Tweaks] (CraftingTweaks_1.12-8.1.1.jar) 
	UCHIJA	forestry{5.4.0.116} [Forestry] (forestry_1.12-5.4.0.116.jar) 
	UCHIJA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJA	gravestone{1.8.2} [Gravestone Mod] (gravestone-1.8.2.jar) 
	UCHIJA	harvest{1.12-1.2.2-14} [Harvest] (Harvest-1.12-1.2.2-14.jar) 
	UCHIJA	intwheel{1.2.6} [Interaction Wheel] (intwheel-1.12-1.2.6.jar) 
	UCHIJA	ironchest{1.12-7.0.28.814} [Iron Chest] (ironchest-1.12-7.0.28.814.jar) 
	UCHIJA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCHIJA	jei{4.7.0.67} [Just Enough Items] (jei_1.12-4.7.0.67.jar) 
	UCHIJA	journeymap{1.12-5.4.7b3} [JourneyMap] (journeymap-1.12-5.4.7b3.jar) 
	UCHIJA	jeresources{0.7.0.10} [Just Enough Resources] (JustEnoughResources-1.12-0.7.0.10.jar) 
	UCHIJA	llor{1.1.4-mc1.12} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.4-mc1.12.jar) 
	UCHIJA	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCHIJA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCHIJA	nmsot{1.2.1-mc1.12} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.1-mc1.12.jar) 
	UCHIJA	notenoughwands{1.5.6} [Not Enough Wands] (notenoughwands-1.12-1.5.6.jar) 
	UCHIJA	reborncore{3.1.0.55} [Reborn Core] (RebornCore-1.12-3.1.0.55-universal.jar) 
	UCHIJA	quantumstorage{4.3.4} [QuantumStorage] (QuantumStorage-1.12-4.3.4.jar) 
	UCHIJA	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCHIJA	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCHIJA	refinedstorage{1.5.5} [Refined Storage] (refinedstorage-1.5.5.jar) 
	UCHIJA	silentlib{2.2.2} [Silent Lib] (SilentLib-1.12-2.2.2-70.jar) 
	UCHIJA	silentgems{2.3.17} [Silent's Gems] (SilentsGems-1.12-2.3.17-188.jar) 
	UCHIJA	soulshardstow{1.12-2.7.2-51} [Soul Shards - The Old Ways] (SoulShards-TOW-1.12-2.7.2-51.jar) 
	UCHIJA	storagedrawers{1.12-5.1.0} [Storage Drawers] (StorageDrawers-1.12-5.1.0.jar) 
	UCHIJA	techreborn{2.5.0.99} [Tech Reborn] (TechReborn-1.12-2.5.0.99-universal.jar) 
	UCHIJA	theoneprobe{1.4.9} [The One Probe] (theoneprobe-1.12-1.4.9.jar) 
	UCHIJA	usefulnullifiers{1.4.0} [Useful Nullifiers] (usefulnullifiers-1.4.0.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
RebornCoreASM (RebornCore-1.12-3.1.0.55-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.1.0.55
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.21.0.2365
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by SilentChaos512** [comment]
There's no mention of it in the changelog, but it seems like Forge removed IPerspectiveAwareModel, which tools use for rendering. I'll see what I can figure out.
