### ISSUE TITLE
Server crash on login - EntityChaosNodePacket to blame?

### ISSUE THREAD

**Issue by rmonk** [SilentChaos512/SilentGems#175]
If I leave the server running for awhile with noone around, then log in, I will get a partial login (some chunks appear, etc) but then it will hang for 60 seconds.  Then I will get a disconnect and the server will be shut down.  Below is the error, attached is the crash log.

I think it's trying to queue up too many chaos packets from the passive pylons because nobody has been on to update that chunk?

(https://github.com/SilentChaos512/SilentGems/files/1121778/crash-2017-07-04_06.40.21-server.txt)[crash-2017-07-04_06.40.21-server.txt]
```
java.lang.Error
        at net.minecraft.world.chunk.Chunk.func_177414_a(Chunk.java:903)
        at net.minecraft.world.World.func_175674_a(World.java:2976)
        at net.minecraft.world.

World.func_72839_b(World.java:2959)
        at net.minecraft.world.World.func_184144_a(World.java:1356)
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:710)
        at net.silentchaos512.lib.util.EntityHelper.moveSelf(EntityHelper.java:19)
        at net.silentchaos512.gems.entity.packet.EntityChaosNodePacket.func_70030_z(EntityChaosNodePacket.java:98)
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:378)
        at net.minecraft.world.World.func_72866_a(World.java:1965)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
        at net.minecraft.world.World.func_72870_g(World.java:1934)
        at net.minecraft.world.World.func_72939_s(World.java:1748)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by SilentChaos512** [comment]
Try enabling the "Direct Transfer" config under the "chaos" category in the config file. It stops Chaos packets from spawning and just transfers the energy instead.

**Comment by rmonk** [comment]
Confirmed, that works around it!
