### ISSUE TITLE
1.11.2 Crash when placing passive pylon

### ISSUE THREAD

**Issue by mackie419** [SilentChaos512/SilentGems#176]
When I place the passive pylon my game keeps crashing. here is the crash log. I even updated to the newest version of forge also. and it even crashed in a creative new world and all i placed was the charging table and as soon as i place the passive pylon the game crashes.

Description: Rendering Block Entity

java.lang.NoSuchMethodError: net.minecraftforge.client.model.ModelLoader.defaultTextureGetter()Ljava/util/function/Function;
	at net.silentchaos512.gems.client.render.models.ModelHelper.bake(ModelHelper.java:48)
	at net.silentchaos512.gems.client.render.models.ModelPylon.<init>(ModelPylon.java:23)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:30)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:16)
	at net.silentchaos512.lib.client.render.tileentity.TileEntitySpecialRendererSL.func_180535_a(TileEntitySpecialRendererSL.java:12)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:150)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:128)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:703)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.silentchaos512.gems.client.render.models.ModelHelper.bake(ModelHelper.java:48)
	at net.silentchaos512.gems.client.render.models.ModelPylon.<init>(ModelPylon.java:23)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:30)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:16)
	at net.silentchaos512.lib.client.render.tileentity.TileEntitySpecialRendererSL.func_180535_a(TileEntitySpecialRendererSL.java:12)

-- Block Entity Details --
Details:
	Name: tile.silentgems:chaospylon // net.silentchaos512.gems.tile.TileChaosPylon
	Block type: ID #2929 (tile.ChaosPylon // net.silentchaos512.gems.block.BlockChaosPylon)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (47,64,230), Chunk: (at 15,4,6 in 2,14; contains blocks 32,0,224 to 47,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #2929 (tile.ChaosPylon // net.silentchaos512.gems.block.BlockChaosPylon)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:150)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:128)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:703)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)

**Comment by SilentChaos512** [comment]
Sorry for the trouble, I'll get it fixed as soon as possible.

**Comment by mackie419** [comment]
No problem. You have done a great job on the mod. Just wanted to give you a heads up about the error. Take your time.
