### ISSUE TITLE
Crash  passive pylon gets into field of view

### ISSUE THREAD

**Issue by darkphan** [SilentChaos512/SilentGems#177]
Versions:

MC 1.10.2
SilentLib: 1.10.2-2.2.5-65
SilentsGems: 1-12.2.4.0-202

Had a passive pylon placed, updated server to the above versions and when logging in as soon as I look int he direction of a pylon the client crashes.

Crash Report (hope this enough from it):

`Description: Rendering Block Entity

java.lang.NoSuchMethodError: net.minecraftforge.client.model.ModelLoader.defaultTextureGetter()Ljava/util/function/Function;
	at net.silentchaos512.gems.client.render.models.ModelHelper.bake(ModelHelper.java:48)
	at net.silentchaos512.gems.client.render.models.ModelPylon.<init>(ModelPylon.java:23)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:30)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:16)
	at net.silentchaos512.lib.client.render.tileentity.TileEntitySpecialRendererSL.func_180535_a(TileEntitySpecialRendererSL.java:12)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.silentchaos512.gems.client.render.models.ModelHelper.bake(ModelHelper.java:48)
	at net.silentchaos512.gems.client.render.models.ModelPylon.<init>(ModelPylon.java:23)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:30)
	at net.silentchaos512.gems.client.render.tile.RenderTileChaosPylon.clRender(RenderTileChaosPylon.java:16)
	at net.silentchaos512.lib.client.render.tileentity.TileEntitySpecialRendererSL.func_180535_a(TileEntitySpecialRendererSL.java:12)

-- Block Entity Details --
Details:
	Name: tile.silentgems:ChaosPylon // net.silentchaos512.gems.tile.TileChaosPylon
	Block type: ID #1608 (tile.ChaosPylon // net.silentchaos512.gems.block.BlockChaosPylon)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (71,13,722), Chunk: (at 7,0,2 in 4,45; contains blocks 64,0,720 to 79,255,735), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Actual block type: ID #1608 (tile.ChaosPylon // net.silentchaos512.gems.block.BlockChaosPylon)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
`

**Comment by SilentChaos512** [comment]
I'm aware of the issue, looking for a fix. Sorry for the trouble.
