### ISSUE TITLE
Crash when trying to Fly in 1.11.2

### ISSUE THREAD

**Issue by mackie419** [SilentChaos512/SilentGems#178]
Keep getting this crash when trying to fly. All that is on the crystal is flight. This is for version 1.11.2. I do have the most current version of Silent Gems installed.

Time: 7/9/17 7:45 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.renderer.Tessellator.func_178180_c()Lnet/minecraft/client/renderer/BufferBuilder;
	at net.silentchaos512.gems.item.ItemChaosGem$Gui.drawRect(ItemChaosGem.java:542)
	at net.silentchaos512.gems.item.ItemChaosGem$Gui.renderGameOverlay(ItemChaosGem.java:509)
	at net.silentchaos512.gems.event.GemsClientEvents.onRenderGameOverlay(GemsClientEvents.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_761_GemsClientEvents_onRenderGameOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:695)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.silentchaos512.gems.item.ItemChaosGem$Gui.drawRect(ItemChaosGem.java:542)
	at net.silentchaos512.gems.item.ItemChaosGem$Gui.renderGameOverlay(ItemChaosGem.java:509)
	at net.silentchaos512.gems.event.GemsClientEvents.onRenderGameOverlay(GemsClientEvents.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_761_GemsClientEvents_onRenderGameOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:695)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171)

**Comment by SilentChaos512** [comment]
Seems I didn't do as good of a job fixing the rendering issues as I thought. Easy enough to fix, I'll find them all this time.
