### ISSUE TITLE
Tool Soul Error when harvesting Redstone Ore

### ISSUE THREAD

**Issue by dotty-dev** [SilentChaos512/SilentGems#262]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.5-256
Silent Lib Version: 2.2.16-97
Modpack and Version (if applicable): N/A

### Expected behavior

- Harvesting Redstone Ore with Gem Pickaxe with equipped Soul, leveling tool soul + getting Redstone Dust

### Actual behaviour

- Block is removed on Client side, Server is however giving an error and when trying to right click the harvested block on client side it will pop back up

### Steps to reproduce the problem

1. Equip Gem Tool with Soul
2. Harvest Redstone
3. ...
4. Get error in Console, server also may or may not restart

Single Player (opened to lan for gamemode changing) with only silent gems + lib gives this: 

[10:38:30] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Stack can not be invalid!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:481) ~[OreDictionary.class:?]
	at net.silentchaos512.gems.lib.soul.ToolSoul.getXpForBlockHarvest(ToolSoul.java:212) ~[ToolSoul.class:?]
	at net.silentchaos512.gems.util.ToolHelper.onBlockStartBreak(ToolHelper.java:679) ~[ToolHelper.class:?]
	at net.silentchaos512.gems.item.tool.ItemGemPickaxe.onBlockStartBreak(ItemGemPickaxe.java:144) ~[ItemGemPickaxe.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:302) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:702) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

Crash report from server crashing is attached
[crash-2017-12-18_17.29.06-server.txt](https://github.com/SilentChaos512/SilentGems/files/1571399/crash-2017-12-18_17.29.06-server.txt)
 
EDIT: The server was still running the Alpha build but the error stays the same with the new beta one, it just did not crash yet therfore i added the latest crash i got

**Comment by SilentChaos512** [comment]
Thanks for reporting. I always forget how weird redstone ore is.
