### ISSUE TITLE
[1.7.10] crash when right clicking growing fluffy puffs

### ISSUE THREAD

**Issue by 1skandar** [SilentChaos512/SilentGems#29]
Right click to harvest works just fine on grown fluffy puffs, but crashes if you accidentally click on an immature plant:
java.lang.NullPointerException: Unexpected error
	at net.silentchaos512.gems.block.FluffyPlantBlock.func_149727_a(FluffyPlantBlock.java:35)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by SilentChaos512** [comment]
Looks like it was caused by having an empty hand. Silly mistake on my part. Other versions appear fine, just 1.7.10 is affected.

**Comment by 1skandar** [comment]
Thank you much for the quick reply and quick fix.
