### ISSUE TITLE
1.12.2 server wont start up.

### ISSUE THREAD

**Issue by AdaraChristine** [SilentChaos512/SilentGems#291]
1.12.2 Versions

Minecraft Version: 14.23.2.2611
Silent's Gems Version: SilentsGems-1.12-2.6.9-264
Silent Lib Version: SilentLib-1.12-2.2.16-97

### Expected behavior

Server start

### Actual behaviour

Server crash

Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.silentchaos512.gems.item.armor.ItemGemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
	at net.silentchaos512.gems.util.ToolHelper.addExampleRecipe(ToolHelper.java:1147)
	at net.silentchaos512.gems.util.ToolHelper.addExampleRecipe(ToolHelper.java:1109)
	at net.silentchaos512.gems.item.armor.ItemGemArmor.addRecipes(ItemGemArmor.java:370)
	at net.silentchaos512.lib.registry.SRegistry.addRecipes(SRegistry.java:362)
	at net.silentchaos512.lib.registry.SRegistry$EventHandler.registerRecipes(SRegistry.java:474)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_325_EventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

https://pastebin.com/DpQiK2Mm

**Comment by smithnc07** [comment]
I also got the same error on the newer forge. 
Forge Version: 14.23.2.2623
Silent's Gems Version: SilentsGems-1.12-2.6.9-264
Silent Lib Version: SilentLib-1.12-2.2.16-97

**Comment by SilentChaos512** [comment]
Uploading version 2.6.9b. Clients should not need to update.

**Comment by smithnc07** [comment]
Awesome, thanks for the quick fix. I have applied the update and tested. I can start the server like normal.
Thanks!
