### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Mr-DLC** [SilentChaos512/SilentGems#34]
Everytme I open Minecraft with this mod, it crashes. I will send a crash report soon

**Comment by Mr-DLC** [comment]
here is the crash report

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 25/04/16 4:25 PM
Description: Initializing game

java.lang.IllegalArgumentException: Duplicate enchantment id! class net.silentchaos512.gems.enchantment.EnchantmentLumberjack and class net.darkhax.moreswords.enchantment.EnchantmentIgnite Enchantment ID:130
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:64)
	at net.silentchaos512.gems.enchantment.EnchantmentLumberjack.<init>(EnchantmentLumberjack.java:27)
	at net.silentchaos512.gems.enchantment.ModEnchantments.init(ModEnchantments.java:28)
	at net.silentchaos512.gems.SilentGems.preInit(SilentGems.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:64)
	at net.silentchaos512.gems.enchantment.EnchantmentLumberjack.<init>(EnchantmentLumberjack.java:27)
	at net.silentchaos512.gems.enchantment.ModEnchantments.init(ModEnchantments.java:28)
	at net.silentchaos512.gems.SilentGems.preInit(SilentGems.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 179611032 bytes (171 MB) / 398905344 bytes (380 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1808 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1808.jar) 
	UCH	Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808.jar) 
	UCH	moSwords{v1} [moSwords] ([1.8.9]moSwords-v1.jar) 
	UCH	advancedswords{1.1.1} [Advanced Swords] (advancedswords-1.1.1.jar) 
	UCH	animalbikes{1.8} [Animal Bikes] (Animal-Bikes-Mod-1.8.9.jar) 
	UCH	armorplus{1.9.0-1.8.9} [ArmorPlus] (ArmorPlusMod1.9.0(1.8.9).jar) 
	UCH	basemetals{1.8.0} [Base Metals] (BaseMetals_1.8.9-1.8.0.jar) 
	UCH	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1620-universal.jar) 
	UCH	JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
	UCH	BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry] (Blood-Magic-Mod-1.8.9.jar) 
	UCH	catwalks{0.1.0} [Catwalks Mod] (catwalks-0.1.0.jar) 
	UCH	chancecubes{@VERSION@} [Chance Cubes] (ChanceCubes-1.8.9-1.6.2.76.jar) 
	UCH	cyclopscore{0.5.3} [Cyclops Core] (CyclopsCore-1.8.9-0.5.3.jar) 
	UCH	colossalchests{1.3.3} [Colossal Chests] (ColossalChests-1.8.9-1.3.3.jar) 
	UCH	customnpcs{1.8.9_beta} [CustomNPCs] (CustomNpcs_1.8.9_beta(21feb16).jar) 
	UCH	ElementalItems{6.1} [Elemental Items Mod] (ElementalItemsMod_6.1-1.8.9.jar) 
	UCH	FunOres{1.1.3} [Fun Ores] (FunOres-1.8.9-1.1.3-55.jar) 
	UCH	grapple_hooks{1.0.4} [Grapple Hooks] (Grapple Hooks-1.8.9-1.0.4.jar) 
	UCH	InventoryPets{1.4.0} [Inventory Pets] (inventorypets-1.8.9-1.4.0.jar) 
	UCH	ironbackpacks{1.8.9-2.0.2} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.2.jar) 
	UCH	IronChest{6.0.119.765} [Iron Chest] (ironchest-1.8.9-6.0.119.765.jar) 
	UCH	lucky{7.0.2} [Lucky Block] (LuckyBlock_1-8-9_v7-0-2.zip) 
	UCH	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCH	MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
	UCH	MSM3{3.1.0.123} [More Swords 3] (MoreSwords-1.8.9-3.1.0.123.jar) 
	UCH	papertazermod{1.0} [Papertazers Base Mod] (Papertazer Base Mod-1.1.jar) 
	UCH	pattysmoretools{1.0} [PattysMoreTools] (PattysMoreTools-1.8.9-1.0.jar) 
	UCH	ProjectE{1.8.9-PE1.1.4} [ProjectE] (ProjectE-1.8.9-PE1.1.4.jar) 
	UCH	reinforcedTools{1.4.0} [ReinforcedTools] (ReinforcedTools-1.4.0-MC1.8.9.jar) 
	UCE	SilentGems{1.3.12b} [Silent's Gems] (SilentsGems-1.8.9-1.3.12b-110 (1).jar) 
	UCH	skatemod{2.1} [Skateboard Mod] (Skateboard Mod-2.1.jar) 
	UCH	SuperMultiDrills{1.3.0-beta4} [Super Multi-Drills] (SuperMultiDrills-1.8.9-1.3.0-beta4-26 (1).jar) 
	UCH	tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
	UCH	uniquemovement{1.0} [Unique Movement Mod] (Unique Movement-1.0.jar) 
	UCH	unlogicii{4.2.1.50} [UnLogic II] (UnLogicII-4.2.1.50.jar) 
	UCH	unlogiciivc{1.5} [UnLogic II Version Checker] (UnLogicII-4.2.1.50.jar) 
	UCH	weaponcaseloot{2.0.0} [WeaponCaseLoot] (weaponcaseloot-2.0.0.jar) 
	UCH	wonderfulwands{1.8.0} [Wonderful Wands] (Wonderful-Wands-Mod-1.8.9.jar) 
	UCH	XaeroMinimap{1.8.7} [Xaero's Minimap] (Xaeros_Minimap_1.8.7_Forge_1.8.9.jar) 
	UCH	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerDebug (Enabled/Not Forced)

	Launched Version: 1.8.9-forge1.8.9-11.15.1.1808
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R5 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1101.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-7410 APU with AMD Radeon R5 Graphics

**Comment by SilentChaos512** [comment]
Duplicate enchantment ID, that's something you will need to fix. Change either Lumberjack from Silent's Gems, or Ignite from More Swords. Most mods let you change enchantment ID's in their config files. I'm not sure if there is any easy way to check available ID's or not. Just try large numbers less than 256 until something works.
