### ISSUE TITLE
Silent Gem's Armor and Modern Warfare Weapons CTD

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/SilentGems#342]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12.2-2.8.5-299.jar
Silent Lib Version: 1.12.2-3.0.6-154.jar
Modpack and Version (if applicable): Resurgence v0.0.2

### Expected behavior

Using a weapon from Modern Warfare mod while Silent Gem armor is equipped.

### Actual behaviour

Equipping the Armor and attempting to equip the gun fires this error;

`java.lang.NullPointerException: null
	at net.minecraft.client.model.ModelBase.func_178686_a(ModelBase.java:62) ~[bqf.class:?]
	at net.minecraft.client.model.ModelBiped.func_178686_a(SourceFile:292) ~[bpx.class:?]
	at net.silentchaos512.gems.item.armor.ItemGemArmor.getArmorModel(ItemGemArmor.java:196) ~[ItemGemArmor.class:?]
	at net.minecraftforge.client.ForgeHooksClient.getArmorModel(ForgeHooksClient.java:231) ~[ForgeHooksClient.class:?]
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.getArmorModelHook(CompatibleWeaponRenderer.java:630) ~[CompatibleWeaponRenderer.class:?]
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.renderLeftArm(CompatibleWeaponRenderer.java:487) ~[CompatibleWeaponRenderer.class:?]
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.renderItem(CompatibleWeaponRenderer.java:314) ~[CompatibleWeaponRenderer.class:?]
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:153) ~[CompatibleWeaponRenderer.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:122) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:144) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184394_a(RenderItem.java:270) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184392_a(RenderItem.java:251) ~[bzw.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_184392_a(CCRenderItem.java:305) ~[CCRenderItem.class:?]
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:75) ~[buu.class:?]
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:432) ~[buu.class:?]
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:333) ~[buu.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:776) ~[buq.class:?]
	at thebetweenlands.client.handler.ShaderHandler.onRenderWorldLast(ShaderHandler.java:79) ~[ShaderHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2467_ShaderHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:181) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1432) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

### Steps to reproduce the problem

1. Enter world and equip any Silent Gem Armor
2. Attempt to equip a firearm - Glock was used in crash report
3. Crashes to desktop - server remains stable.

May be issue with another mod, and I apologize if this is a known issue, or has been previously reported.

**Comment by SilentChaos512** [comment]
Not sure I can fix this one. Has it been reported to Modern Warfare as well?

**Comment by ghost** [comment]
I will report it to them immediately, and see what they say.

Thank you for the reply

**Comment by ghost** [comment]
Just update to you, got a reply from Modern Warfare Author,

" I stopped working on the mod independently. I'm working on other things right now. "

For now an option is to not use the firearms while you wear the armor.  Our users agree and as long as they don't, there isn't an issue.  Don't know if you want to archive this report or close it entirely.

Thanks so much for the quick replies though!
