### ISSUE TITLE
"Caught an odd exception in ItemEnchantmentToken#getModelKey."

### ISSUE THREAD

**Issue by Mercurious1** [SilentChaos512/SilentGems#369]
### Versions

- **Silent's Gems**:   1.12.2-2.8.17+319
- **Silent Lib**:   1.12.2-3.0.13+167
- **Forge**:  14.23.5.2836
- **Modpack** (if applicable): Custom 

### Expected behavior

I don't know

[04:51:42] [Server thread/ERROR] [Silent's Gems]: ********************************************************************************
[04:51:42] [Server thread/ERROR] [Silent's Gems]: * Caught an odd exception in ItemEnchantmentToken#getModelKey. This will only be
[04:51:42] [Server thread/ERROR] [Silent's Gems]: * logged once.
[04:51:42] [Server thread/ERROR] [Silent's Gems]: * Offending token: 1xitem.silentgems.enchantmenttoken@0
[04:51:42] [Server thread/ERROR] [Silent's Gems]: * Offending enchantment:
[04:51:42] [Server thread/ERROR] [Silent's Gems]: * com.teammetallurgy.aquaculture.enchantments.Enchan
[04:51:42] [Server thread/ERROR] [Silent's Gems]: * mentHeavyLine@4f77b8f0 (enchantment.aquacultureHeavyLine)
[04:51:42] [Server thread/WARN] [Silent's Gems]: *  at net.silentchaos512.gems.item.ItemEnchantmentToken.getModelKey(ItemEnchantmentToken.java:244)
[04:51:42] [Server thread/WARN] [Silent's Gems]: *  at net.silentchaos512.gems.item.ItemEnchantmentToken.compareEnchantmentNames(ItemEnchantmentToken.java:324)
[04:51:42] [Server thread/WARN] [Silent's Gems]: *  at java.util.TimSort.binarySort(Unknown Source)
[04:51:42] [Server thread/WARN] [Silent's Gems]: *  at java.util.TimSort.sort(Unknown Source)
[04:51:42] [Server thread/WARN] [Silent's Gems]: *  at java.util.Arrays.sort(Unknown Source)
[04:51:42] [Server thread/WARN] [Silent's Gems]: *  at java.util.ArrayList.sort(Unknown Source)...
[04:51:42] [Server thread/ERROR] [Silent's Gems]: ********************************************************************************
### Actual behaviour

Nothing noticeable

### Steps to reproduce the problem

1. I have 450 mods in this pack, it runs smooth, no crash, no lag, but saw in log and decided to tell you
2.
3.

**Comment by SilentChaos512** [comment]
Haven't seen that in a while. That log message comes from issue #139. I think this is the first time anyone has reported the actual log output. I might know how to fix this now. But in the meantime, this bug shouldn't cause you any issues.

**Comment by Mercurious1** [comment]
Yea, figured it isn't a big issue, since I've had it in my game for a few weeks without any issue, but havent played through the whole mod yet ^_^ Just starting to optimize my pack, so, went through startup log to try to clear out any issues I could find :)
