### ISSUE TITLE
1.16.1 Crash when trying to set up teleporters

### ISSUE THREAD

**Issue by Rickterr** [SilentChaos512/SilentGems#497]
## Versions

- **Silent's Gems**: SilentGems-1.16.1-3.6.3+100.jar
- **Silent Gear**: SilentGear-1.16.1-2.1.1+162.jar 
- **Silent Lib**: SilentLib-1.16.1-4.7.1+59.jar
- **Forge**: 32.0.108
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Right Clicking on a Teleporter or Teleporter Anchor with a link tool or a return charm and linking them to said block

## Actual Behavior

When Rightclicking on a teleporter or teleporter anchor with a link tool or a return charm results in a crash to desktop

## Links/Images

- full crash : https://pastebin.com/jR3CgF0b
note: first experienced in a heavily modded client, set up a brand new one using only silent lib/gems/gear/mechanisms/JEI to see if i could reproduce, and i could, so i'm posting the crash from the more "sanitized" game
## Steps to Reproduce the Problem

1. take a charm/link tool
2. right click on a teleporter/anchor
3. crash

**Comment by ProsperCraft** [comment]
Same problem with 1.16.3-

`java.util.IllegalFormatConversionException: d != net.minecraft.util.RegistryKey
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793) ~[?:1.8.0_51] {}
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747) ~[?:1.8.0_51] {}
	at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_51] {}
	at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_51] {}
	at java.lang.String.format(String.java:2928) ~[?:1.8.0_51] {}
	at net.silentchaos512.lib.util.DimPos.toString(DimPos.java:146) ~[?:4.8.1+61] {re:classloading}`

https://gist.github.com/ProsperCraft/19793a62a325a6b94c4360b6b83e6e5c

SilentGems-1.16.3-3.7.0+103
SilentGear-1.16.3-2.2.0+164
SilentLib-1.16.3-4.8.1+61
