### ISSUE TITLE
silentgear dagger

### ISSUE THREAD

**Issue by aldohe** [SilentChaos512/SilentGems#514]
---- Minecraft Crash Report ----
// There are four lights!

Time: 7/12/20 03:29 PM
Description: Rendering item

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[guava-21.0.jar:?] {}
	at net.silentchaos512.gear.client.model.gear.GearModelOverrideList.func_239290_a_(GearModelOverrideList.java:76) ~[?:2.3.7+176] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_184393_a(ItemRenderer.java:374) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:468) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:457) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:39) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:25) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:179) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:159) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:185) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.recipes.RecipesGui.func_230430_a_(RecipesGui.java:243) ~[?:7.6.0.58] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:286) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:717) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.3.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$455/1766451528.call(Unknown Source) [forge-1.16.4-35.1.3.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[guava-21.0.jar:?] {}
	at net.silentchaos512.gear.client.model.gear.GearModelOverrideList.func_239290_a_(GearModelOverrideList.java:76) ~[?:2.3.7+176] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_184393_a(ItemRenderer.java:374) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Item being rendered --
Details:
	Item Type: dagger
	Registry Name: silentgear:dagger
	Item Damage: 0
	Item NBT: {SGear_Data:{Construction:{Tier:0},Rendering:{},Properties:{}},Damage:0}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:468) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:457) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:39) ~[?:7.6.0.58] {re:classloading}

-- Ingredient being rendered --
Details:
	Mod Name: Silent Gear
	Registry Name: silentgear:dagger
	Display Name: Dagger
	String Name: 1 dagger
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:271) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:182) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:159) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:185) ~[?:7.6.0.58] {re:classloading}
	at mezz.jei.gui.recipes.RecipesGui.func_230430_a_(RecipesGui.java:243) ~[?:7.6.0.58] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:286) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:717) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.3.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$455/1766451528.call(Unknown Source) [forge-1.16.4-35.1.3.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- JEI render details --
Details:
	Unique Id (for Blacklist): silentgear:dagger
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1 dagger silentgear:dagger nbt:{SGear_Data:{Construction:{Tier:0},Rendering:{},Properties:{}},Damage:0}
	Filter Text: 
	Edit Mode Enabled: false
	Debug Mode Enabled: false

-- Screen render details --
Details:
	Screen name: mezz.jei.gui.recipes.RecipesGui
	Mouse location: Scaled: (615, 266). Absolute: (1230.000000, 532.000000)
	Screen size: Scaled: (640, 360). Absolute: (1280, 720). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['javon77'/150, l='ClientLevel', x=80.70, y=54.00, z=26.40]]
	Chunk stats: Client Chunk Cache: 729, 530
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,66,64), Chunk: (at 0,4,0 in 4,4; contains blocks 64,0,64 to 79,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 179961 game time, 188805 day time
	Server brand: forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3478391640 bytes (3317 MB) / 5268045824 bytes (5024 MB) up to 5268045824 bytes (5024 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx5000M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.3.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.3.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.3
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.3-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		SimpleStorageNetwork-1.16.3-1.2.1.jar             |Simple Storage Network        |storagenetwork                |1.16.3-1.2.1        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Gobber2-1.16.4-2.3.40.jar                         |Gobber 2                      |gobber2                       |2.3.40              |DONE      |NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		SilentLib-1.16.3-4.9.0+63.jar                     |Silent Lib                    |silentlib                     |4.9.0+63            |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |DONE      |NOSIGNATURE
		SilentGear-1.16.3-2.3.7+176.jar                   |Silent Gear                   |silentgear                    |2.3.7+176           |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |DONE      |NOSIGNATURE
		forbidden_arcanus-1.16.3-1.0.2.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.16.3-1.0.2        |DONE      |NOSIGNATURE
		SilentGems-1.16.3-3.7.3+106.jar                   |Silent's Gems 3               |silentgems                    |3.7.3+106           |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.3-universal.jar                 |Forge                         |forge                         |35.1.3              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.4-1.16.jar                |TLSkinCape                    |tlskincape                    |1.6                 |DONE      |19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		Neat+1.7-24.jar                                   |Neat                          |neat                          |1.7-24              |DONE      |NOSIGNATURE
		Xaeros_Minimap_20.28.2_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.28.2             |DONE      |NOSIGNATURE
		XaerosWorldMap_1.11.4_Forge_1.16.4.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.4              |DONE      |NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |DONE      |NOSIGNATURE
	Crash Report UUID: 5cf8f33f-1839-432b-b06b-d919eebccb0f
	Launched Version: ForgeOptiFine 1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.30, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 457.30
	OpenGlRenderer: GeForce GT 710/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by SilentChaos512** [comment]
Follow the issue template next time. This is most likely an Optifine issue. Nothing I can do about it. Try again without Optifine installed.
