### ISSUE TITLE
1.15.2 unknown crash

### ISSUE THREAD

**Issue by SouthWT** [SilentChaos512/SilentGems#529]
minecraft 1.15.2 multimc 5 
forge 31.2.43
Silent Gems 1.15.2  3.6.2  98
Silent Gear 1.15.2 1.11.4  187
Silent Lib  1.15.2  4.6.6   59

---- Minecraft Crash Report ----
// Don't do that.

Time: 2/26/21 11:10 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: silentgems:soul_urn
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:classloading}
	at net.silentchaos512.lib.registry.RegistryObjectWrapper.get(RegistryObjectWrapper.java:28) ~[?:4.6.6+59] {re:classloading}
	at net.silentchaos512.gems.lib.ColorHandlers.onBlockColors(ColorHandlers.java:30) ~[?:3.6.2+98] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.43-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
	at net.silentchaos512.lib.registry.RegistryObjectWrapper.get(RegistryObjectWrapper.java:28)
	at net.silentchaos512.gems.lib.ColorHandlers.onBlockColors(ColorHandlers.java:30)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at java.util.HashMap.forEach(Unknown Source)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1621811552 bytes (1546 MB) / 2748841984 bytes (2621 MB) up to 5592580096 bytes (5333 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6000m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.43-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.43-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.43-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.43-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.43-launcher.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.43
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.10.0
	Mod List: 
		enchantedbookredesign-2.0a.jar Enchanted Book Redesign {enchantedbookredesign@2.0a CREATE_REGISTRIES}
		aiotbotania-1.15.2-1.2.3.jar AIOT Botania {aiotbotania@1.2.3 CREATE_REGISTRIES}
		futuremc-1.15.2-1.1.0.jar Future MC {futuremc@1.15.2-1.1.0 CREATE_REGISTRIES}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 CREATE_REGISTRIES}
		Neat+1.6-22.jar Neat {neat@1.6-22 CREATE_REGISTRIES}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 CREATE_REGISTRIES}
		CTM-MC1.15.2-1.1.2.14.jar ConnectedTexturesMod {ctm@MC1.15.2-1.1.2.14 CREATE_REGISTRIES}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 CREATE_REGISTRIES}
		gemsnjewels-1.15.2-0.17.0.jar Gems & Jewels {gemsnjewels@0.17.0 CREATE_REGISTRIES}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 CREATE_REGISTRIES}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 CREATE_REGISTRIES}
		randompatches-1.15.2-1.22.1.1.jar RandomPatches {randompatches@1.15.2-1.22.1.1 CREATE_REGISTRIES}
		Ma-Essentials-1.15.2-3.1.1.jar Ma Essentials {maessentials@1.15.2-3.1.1 CREATE_REGISTRIES}
		FpsReducer-mc1.15.2-1.18.jar FPS Reducer {fpsreducer@mc1.15.2-1.18 CREATE_REGISTRIES}
		carryon-1.15.2-1.13.0.5.jar Carry On {carryon@1.13.0.5 CREATE_REGISTRIES}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 CREATE_REGISTRIES}
		ftb-teams-1.0.0.6.jar FTB Teams {ftbteams@1.0.0.6 CREATE_REGISTRIES}
		EnchantedGApple1-15-2.jar Craftable Notch Apple {craftable_notch_apple@1.0.0 CREATE_REGISTRIES}
		SimpleOres2-1.15.2-2.1.10.2.jar Simple Ores {simpleores@1.15.2-2.1.10.2 CREATE_REGISTRIES}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 CREATE_REGISTRIES}
		mcw-bridges-1.0.5-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.5 CREATE_REGISTRIES}
		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 CREATE_REGISTRIES}
		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 CREATE_REGISTRIES}
		crashutilities-2.10.jar Crash Utilities {crashutilities@2.10 CREATE_REGISTRIES}
		Ping-1.15.2-1.6.4.jar Ping {ping@1.15.2-1.6.4 CREATE_REGISTRIES}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 CREATE_REGISTRIES}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 CREATE_REGISTRIES}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a CREATE_REGISTRIES}
		ironfurnaces-1.15.2-2.0.4.jar Iron Furnaces {ironfurnaces@2.0.4 CREATE_REGISTRIES}
		ineedthemores-1.15.2-1.3.jar I Need Them Ores {ineedthemores@1.15.2-1.3 CREATE_REGISTRIES}
		dungeons-plus-1.15.2-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 CREATE_REGISTRIES}
		mcw-trapdors-1.0.1-mc1.15.2.jar Macaw's Trapdoors {mcwtrpdoors@1.0.1 CREATE_REGISTRIES}
		mining_dimension-1.15.2-1.0.4.jar Mining World {mining_dimension@1.15.2-1.0.4 CREATE_REGISTRIES}
		SilentGear-1.15.2-1.11.4+187.jar Silent Gear {silentgear@1.11.4+187 CREATE_REGISTRIES}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 CREATE_REGISTRIES}
		simplybackpacks-1.15.2-1.4.11.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.11 CREATE_REGISTRIES}
		pamhc2foodextended-1.15.2-1.0.0.jar Pam's HarvestCraft 2 Food Extended {pamhc2foodextended@version CREATE_REGISTRIES}
		randomenchants-3.1.1.jar Random Enchants {randomenchants@3.1.1 ERROR}
		Einsteinslibrary-1.4_MC1.15.2.jar Einstein's Library {einsteins_library@1.4 CREATE_REGISTRIES}
		CutAndColored-3.1_MC1.15.2.jar Cut And Colored {cutandcolored@3.1 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.7.jar Curios API {curios@FORGE-1.15.2-2.0.2.7 CREATE_REGISTRIES}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 CREATE_REGISTRIES}
		minecraft2discord-forge-1.15.2-2.0.6.jar Minecraft2Discord {minecraft2discord@forge-1.15.2-2.0.6 CREATE_REGISTRIES}
		extlights-2.1.jar Extended Lights {extlights@2.1 CREATE_REGISTRIES}
		TorchBandolier-1.15.2-1.4.0+8.jar Torch Bandolier {torchbandolier@1.4.0+8 CREATE_REGISTRIES}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 CREATE_REGISTRIES}
		ftb-ultimine-1.0.8.5.jar FTB Ultimine {ftbultimine@1.0.8.5 CREATE_REGISTRIES}
		obfuscate-0.5.0-1.15.2.jar Obfuscate {obfuscate@0.5.0 CREATE_REGISTRIES}
		vehicle-mod-0.44.1-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.1 CREATE_REGISTRIES}
		Server_Utils-1.15.2-1.5.2.jar Elrol's Server Utilities {serverutilities@1.15.2-1.5.2 CREATE_REGISTRIES}
		mcw-roofs-2.0.1-mc1.15.2.jar Macaw's Roofs {mcwroofs@2.0.1 CREATE_REGISTRIES}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 CREATE_REGISTRIES}
		mcw-furniture-2.0.1-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@2.0.1 CREATE_REGISTRIES}
		almostalltheores-2.0.3.1.jar Almost All the Ores {almostalltheores@2.0.3.1 CREATE_REGISTRIES}
		SBM-WoodenShears-1.15.2-1.1.0.jar SBM-Wooden Shears {woodenshears@1.0.0 CREATE_REGISTRIES}
		FunOres-1.15.2-2.5.1+17.jar Fun Ores {funores@2.5.1+17 CREATE_REGISTRIES}
		switchbow-1.6.jar Switch-Bow {switchbow@1.6 CREATE_REGISTRIES}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 CREATE_REGISTRIES}
		exoticbirds-1.15.2-1.1.1.jar Exotic Birds {exoticbirds@1.1.1 CREATE_REGISTRIES}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 CREATE_REGISTRIES}
		effortlessbuilding-1.15.2-2.21.jar Effortless Building {effortlessbuilding@1.15.2-2.21 CREATE_REGISTRIES}
		dungeons_gear-1.15.2-1.2.8.jar Dungeons Gear {dungeons_gear@1.2.8 CREATE_REGISTRIES}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 CREATE_REGISTRIES}
		Ma-Enchants-1.15.2-3.1.0.jar Ma Enchants {ma-enchants@1.15.2-3.1.0 CREATE_REGISTRIES}
		torchslabmod-1.15.2_v1.7.0.jar Torch Slab Mod {torchslabmod@1.7.0 CREATE_REGISTRIES}
		MyCommands-1.15.2-02.jar Mycommands Forge {mycommands@1.15.2-02 CREATE_REGISTRIES}
		XPFromHarvest-1.15.2-1.2.1.jar XP From Harvest {xpfromharvest@1.2.1 CREATE_REGISTRIES}
		pamhc2trees-1.15.2-1.0.7.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version CREATE_REGISTRIES}
		mining-helmet-1.15.2-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 CREATE_REGISTRIES}
		craftingstation-3.1.0.jar Crafting Station {craftingstation@3.1.0 CREATE_REGISTRIES}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 CREATE_REGISTRIES}
		FallingTree-1.15.2-2.4.0.jar Falling Tree {falling_tree@2.4.0 CREATE_REGISTRIES}
		wildnature-1.15.2-3.0.jar WildNature {wildnature@3.0 CREATE_REGISTRIES}
		mcw-paintings-1.0.0-mc1.15.2.jar Macaw's Paintings {mcwpaintings@1.0.0 CREATE_REGISTRIES}
		Clumps-5.0.2.6.jar Clumps {clumps@5.0.2.6 CREATE_REGISTRIES}
		comforts-FORGE-1.15.2-2.0.0.4.jar Comforts {comforts@FORGE-1.15.2-2.0.0.4 CREATE_REGISTRIES}
		Gems+and+Crystals-1.15.2-1.2.9.jar Gems and Crystals {gemsandcrystals@1.2.9 CREATE_REGISTRIES}
		decorative_blocks-1.15.2-1.7.jar Decorative Blocks {decorative_blocks@1.7 CREATE_REGISTRIES}
		BasicNetherOres-1.15.2-4.0.3.jar Basic Nether Ores {bno@4.0.3 CREATE_REGISTRIES}
		VanillaTweaks-1.15.2.1.5.30.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.30 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-2.2.4.jar Dungeon Crawl {dungeoncrawl@2.2.4 CREATE_REGISTRIES}
		betteranimalsplus-1.15.2-10.1.0.jar Better Animals Plus {betteranimalsplus@10.1.0 CREATE_REGISTRIES}
		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 CREATE_REGISTRIES}
		inventorypets-2.0.12.jar Inventory Pets {inventorypets@2.0.12 CREATE_REGISTRIES}
		gemsplusplus-1.15.2-V1.8.1-.jar GemsPlusPlus {gemsplusplus@V1.8.1 CREATE_REGISTRIES}
		forge-1.15.2-31.2.43-universal.jar Forge {forge@31.2.43 CREATE_REGISTRIES}
		FasterLadderClimbing-1.15.2-0.2.jar Faster Ladder Climbing {fasterladderclimbing@1.15.2-0.2 CREATE_REGISTRIES}
		[Forge]+GamemodeOverhaul-1.15.2-1.4.2.3.jar GamemodeOverhaul {gamemodeoverhaul@1.15.2-1.4.2.3 CREATE_REGISTRIES}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 CREATE_REGISTRIES}
		colouredchat-1.15.1-1.4.5.jar ColouredChat {colouredchat@1.15.1-1.4.5 CREATE_REGISTRIES}
		forge-1.15.2-31.2.43-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.7.jar The One Probe {theoneprobe@1.15-2.0.7 CREATE_REGISTRIES}
		playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		EasySteel-1.15.2-1.1.79.jar Easy Steel & More {easy_steel@1.1.79 CREATE_REGISTRIES}
		Ma-Chat-1.15.2-3.1.0.jar Ma Chat {ma-chat@1.15.2-3.1.0 CREATE_REGISTRIES}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 CREATE_REGISTRIES}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version CREATE_REGISTRIES}
		locatebiome-1.15.2-v1.0.jar LocateBiome {locatebiome@v1.0 CREATE_REGISTRIES}
		GeneticAnimals-0_5_15.jar Genetic Animals {eanimod@0_5_15 CREATE_REGISTRIES}
		jeiintegration_1.15.2-3.1.1.2.jar JEI Integration {jeiintegration@3.1.1.2 CREATE_REGISTRIES}
		pamhc2foodcore-1.15.2-1.1.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version CREATE_REGISTRIES}
		gravestone-1.17.6.jar Gravestone Mod {gravestone@1.17.6 CREATE_REGISTRIES}
		FastWorkbench-1.15.2-3.1.1.jar FastWorkbench {fastbench@3.1.1 CREATE_REGISTRIES}
		polymorph-FORGE-1.15.2-0.10.jar Polymorph {polymorph@FORGE-1.15.2-0.10 CREATE_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 CREATE_REGISTRIES}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 CREATE_REGISTRIES}
		overworld_quartz-1.15.2-1.0.0.1.jar Overworld Quartz {overworld_quartz@1.0.0.1 CREATE_REGISTRIES}
		PiTweaks-1.15.2-1.2.2.jar CplPibald's Tweaks {pitweaks@1.15.2-1.2.2 CREATE_REGISTRIES}
		Animalium-0.5.3.jar Animalium {animalium@0.5.3 CREATE_REGISTRIES}
		WorldHandler-1.15.2-2.9.1.jar World Handler {worldhandler@1.15.2-2.9.1 CREATE_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
		Actually+Useful+Stonecutter-0.0.1+mc+1.15.2.jar Actually Useful Stonecutter {actuallyusefulstonecutter@0.0.1 mc 1.15.2 CREATE_REGISTRIES}
		MineTogether-1.15.2-4.1.5.jar MineTogether {minetogether@1.15.2-4.1.5 CREATE_REGISTRIES}
		ilikewood-1.15.2-2.2.2.0.jar I Like Wood {ilikewood@1.15.2-2.2.2.0 CREATE_REGISTRIES}
		SilentGems-1.15.2-3.6.2+98.jar Silent's Gems 3 {silentgems@3.6.2+98 CREATE_REGISTRIES}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 CREATE_REGISTRIES}
		forgemod_VoxelMap-1.9.28_for_1.15.2.jar VoxelMap {voxelmap@1.9.28 CREATE_REGISTRIES}
		CHAS+v1.3+for+1.15.jar Craftable Horse Armour {craftablehorsearmour@1.3 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a CREATE_REGISTRIES}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 CREATE_REGISTRIES}
		OresAboveDiamonds-1.15.2-v6.3.1.jar Ores Above Diamonds {oresabovediamonds@6.3.1 CREATE_REGISTRIES}
		morered-1.15.2-1.0.1.0.jar More Red {morered@1.15.2-1.0.1.0 CREATE_REGISTRIES}
		lootbagmod-1.15.1-1.5.3.jar Loot Bag Mod {lootbagmod@1.15.1-1.5.3 CREATE_REGISTRIES}
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce MX130/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.56, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz

**Comment by SilentChaos512** [comment]
In the future, please provide a _link_ to the crash report, as the issue template indicated. (edit) I guess you somehow skipped the template since the bug label is missing...

In 1.15.2, there are cases where a mod can cause a crash, but Forge continues sending events. This causes the blame to be incorrectly pinned on other mods. You'll need to look through your log file. It's usually not too far above the crash report. Forge fixed this bug in 1.16, but not 1.15.
