### ISSUE TITLE
ItemEnchantmentToken Null Pointer Exception on World load

### ISSUE THREAD

**Issue by scottosx** [SilentChaos512/SilentGems#93]
I haven't been able to play with Silent Gem's since the last update (or test new SkyBlock features). Worlds with my personal modpack wouldn't load. I finally got an error log that may point to the issue. Here are the relevant bits of the log.

[10:52:45] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[10:52:45] [Server thread/ERROR] [FML]: Caught exception from Just Enough Items (JEI)
java.lang.ExceptionInInitializerError
	Caused by: java.lang.NullPointerException
	at net.silentchaos512.gems.item.ItemEnchantmentToken.getModelKey(ItemEnchantmentToken.java:238) ~[ItemEnchantmentToken.class:?]
	at net.silentchaos512.gems.item.ItemEnchantmentToken$2.compare(ItemEnchantmentToken.java:316) ~[ItemEnchantmentToken$2.class:?]
	at net.silentchaos512.gems.item.ItemEnchantmentToken$2.compare(ItemEnchantmentToken.java:311) ~[ItemEnchantmentToken$2.class:?]
	at java.util.TimSort.binarySort(TimSort.java:296) ~[?:1.8.0_101]
	at java.util.TimSort.sort(TimSort.java:239) ~[?:1.8.0_101]
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_101]
	at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_101]
	at net.silentchaos512.gems.item.ItemEnchantmentToken.func_150895_a(ItemEnchantmentToken.java:311) ~[ItemEnchantmentToken.class:?]
	at crazypants.enderio.integration.jei.ItemHelper.getValidItems(ItemHelper.java:24) ~[ItemHelper.class:?]
	at crazypants.enderio.integration.jei.DarkSteelUpgradeRecipeCategory.<clinit>(DarkSteelUpgradeRecipeCategory.java:68) ~[DarkSteelUpgradeRecipeCategory.class:?]
	... 41 more

**Comment by SilentChaos512** [comment]
I'm guessing some mod (no idea which) is registering an enchantment incorrectly. Should be easy enough to fix, but I can't reproduce it myself. If you are using the Curse launcher, could you export your profile for me? If not, a full crash report or mod list would be helpful.
